src/LoansReview.WebMvc/Models/ErrorViewModel.cs
using System;

namespace LoansReview.WebMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string Message { get; set; }
    }
}

src/LoansReview.WebMvc/Models/PaginatedItemsViewModel.cs
using LoansReview.WebMvc.Infrastructure;
using System.Collections.Generic;

namespace LoansReview.API.Application.Models
{
    public class PaginatedItemsViewModel
    {
        public int PageIndex { get; private set; }

        public int PageSize { get; private set; }

        public long Count { get; private set; }

        public IEnumerable<LoanApplicationVM> Data { get; private set; }

        public PaginatedItemsViewModel(
            int pageIndex, int pageSize, long count, 
            IEnumerable<LoanApplicationVM> data)
        {
            this.PageIndex = pageIndex;
            this.PageSize = pageSize;
            this.Count = count;
            this.Data = data;
        }
    }
}

src/LoansReview.WebMvc/Controllers/LoanReviewController.cs
using LoansReview.WebMvc.Infrastructure;
using LoansReview.WebMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LoansReview.WebMvc.Controllers
{
    public class LoanReviewController : Controller
    {
        private readonly ILoanService _loanService;

        public LoanReviewController(
            ILoanService loanService)
        {
            _loanService = loanService;
        }

        public async Task<IActionResult> Index(
            [FromQuery] int pageSize = 5,
            [FromQuery] int pageIndex = 0)
        {
            try
            {
                var page = await _loanService.GetPage(pageSize: pageSize, pageIndex: pageIndex);
                return View(page);
            }
            catch (System.Exception ex)
            {
                return View("Error", new ErrorViewModel() { Message = ex.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string loanApplicationId)
        {
            try
            {
                var loan = await _loanService.Detail(loanApplicationId);
                return View(loan);
            }
            catch (System.Exception ex)
            {
                return View("Error", new ErrorViewModel() { Message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(LoanApplicationVM vm)
        {
            try
            {
                await _loanService.UpdateLoanStatus(vm);
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                return View("Error", new ErrorViewModel() { Message = ex.Message });
            }
        }
    }
}

src/LoansReview.WebMvc/Views/LoanReview/Edit.cshtml
@model LoansReview.WebMvc.Infrastructure.LoanApplicationVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Review Loan</h1>

<h4>@Model.LoanApplicationId</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(item => item.LoanApplicationId)
           
            <div class="form-group">
                <label class="control-label">Request Amount</label>
                <input asp-for="RequestAmount" class="form-control" disabled/>
                <span asp-validation-for="RequestAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Total Amount Payable</label>
                <input asp-for="TotalAmountPayable" class="form-control"  disabled/>
                <span asp-validation-for="TotalAmountPayable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Term</label>
                <input asp-for="TermLengthInMonths" class="form-control" disabled/>
                <span asp-validation-for="TermLengthInMonths" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Monthly Payment</label>
                <input asp-for="MonthlyPayment" class="form-control" disabled/>
                <span asp-validation-for="MonthlyPayment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="APR" class="control-label"></label>
                <input asp-for="APR" class="form-control" disabled/>
                <span asp-validation-for="APR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Approval Status</label>

                @Html.DropDownListFor(model => model.ApprovalStatus,
                                (List<SelectListItem>)Model.ApprovalStatuses, htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ApprovalStatus, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Created Date</label>
                <input asp-for="CreatedDate" class="form-control" disabled/>
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/LoansReview.WebMvc/Views/LoanReview/Index.cshtml
@model LoansReview.API.Application.Models.PaginatedItemsViewModel
@using LoansReview.WebMvc.Infrastructure

@{
    ViewData["Title"] = "Index";
}

<h1>Loan Applications</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Ref
            </th>
            <th>
                Created Date
            </th>
            <th>
                Name
            </th>
            <th>
                Home Owner
            </th>
            <th>
                Income (k)
            </th>
            <th>
                Request Amount
            </th>
            <th>
                Total Amount Payable
            </th>
            <th>
                Term (months)
            </th>
            <th>
                Monthly Payment
            </th>
            <th>
                APR
            </th>
            <th>
                Approval Status
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data) {
        <tr>
            <td>
                @item.LoanApplicationId.ToString().Substring(0,8)
            </td>
            <td>
                @item.CreatedDate.ToString("dd MMM yy")
            </td>
            <td>
                @item.User.FullName
            </td>
            <td>
                @{
                    if(item.User.IsHomeOwner == true)
                    {
                        <input type="checkbox" class="form-control" checked disabled >
                    }
                    else 
                    {
                        <input type="checkbox" class="form-control" disabled>
                    }
                }
            </td>
            <td>
                @item.User.AnnualIncomeInThousands.ToString("N2")
            </td>
            <td>
                £@item.RequestAmount.ToString("N2")
            </td>
            <td>
                £@item.TotalAmountPayable.ToString("N2")
            </td>
            <td>
                @item.TermLengthInMonths
            </td>
            <td>
                £@item.MonthlyPayment.ToString("N2")
            </td>
            <td>
                @item.APR%
            </td>
            <td>
                @{
                    if(item.ApprovalStatus == LoanApprovalStatus.InProgress)
                    {
                    <span class="badge badge-primary">@item.ApprovalStatus.ToString()</span>
                    }
                    else if(item.ApprovalStatus == LoanApprovalStatus.Approved)
                    {
                    <span class="badge badge-success">@item.ApprovalStatus.ToString()</span>
                    }
                    else if(item.ApprovalStatus == LoanApprovalStatus.Declined)
                    {
                    <span class="badge badge-danger">@item.ApprovalStatus.ToString()</span>
                    }
                    else
                    {
                    <span class="badge badge-warning">None</span>
                    }
                }

            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  loanApplicationId=item.LoanApplicationId  })
            </td>
        </tr>
        }
    </tbody>
</table>


<div class="container">
    <article class="row">
        <nav>
            <a class="btn btn-secondary"
               id="Previous"
               asp-controller="LoanReview"
               asp-action="Index"
               asp-route-PageIndex="@(Model.PageIndex -1)"
               aria-label="Previous">
                Previous
            </a>

            <span class="esh-pager-item">
                Showing page @(Model.PageIndex + 1)
            </span>

            <a class="btn btn-secondary"
               id="Next"
               asp-controller="LoanReview"
               asp-action="Index"
               asp-route-PageIndex="@(Model.PageIndex + 1)"
               aria-label="Next">
                Next
            </a>
        </nav>
    </article>
</div>

src/LoansReview.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loan Review</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="LoanReview" asp-action="Index">Loan Review</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Loan Review
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>