src/Loans.WebMvc/Models/Application/LoanApplicationVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Loans.WebMvc.Models.Application
{
    public class LoanApplicationVM
    {
        [Required]
        public string Title { get; set; }

        [Required]
        [StringLength(20)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(20)]
        public string Lastname { get; set; }

        public string FullName
        {
            get { return $"{FirstName} {Lastname}".Trim(); }
        }

        [Required]
        [StringLength(150)]
        public string Address { get; set; }

        [Required]
        [DisplayName("Mobile")]
        [RegularExpression(@"^(?:(?:\(?(?:0(?:0|11)\)?[\s-]?\(?|\+)44\)?[\s-]?(?:\(?0\)?[\s-]?)?)|(?:\(?0))(?:(?:\d{5}\)?[\s-]?\d{4,5})|(?:\d{4}\)?[\s-]?(?:\d{5}|\d{3}[\s-]?\d{3}))|(?:\d{3}\)?[\s-]?\d{3}[\s-]?\d{3,4})|(?:\d{2}\)?[\s-]?\d{4}[\s-]?\d{4}))(?:[\s-]?(?:x|ext\.?|\#)\d{3,4})?$",
            ErrorMessage = "Invalid phone number")]
        //[Phone]
        public string MobileNumber { get; set; }

        [Required]
        [DisplayName("Email")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?",
            ErrorMessage = "Invalid Email Address")]
        //[EmailAddress]
        public string EmailAddress { get; set; }

        [Required]
        [DisplayName("Annual Income (in thousands)")]
        [Range(1, 1000)]
        public int AnnualIncome { get; set; }

        [Required]
        [DisplayName("Home Owner")]
        public bool IsHomeOwner { get; set; }

        [DisplayName("Car Registration Number")]
        public string CarRegistrationNumber { get; set; }

        [Required]
        [DisplayName("Loan Request Amount")]
        [Range(1, 500000)]
        public int LoanRequestAmount { get; set; }

        public List<SelectListItem> Titles =>
           GetTitles();
        private List<SelectListItem> GetTitles()
        {
            var result = new List<SelectListItem>();
            result.Add(new SelectListItem { Text = "Mr", Value = "Mr" });
            result.Add(new SelectListItem { Text = "Mrs", Value = "Mrs" });
            result.Add(new SelectListItem { Text = "Miss", Value = "Miss" });
            result.Add(new SelectListItem { Text = "Ms", Value = "Ms" });
            result.Add(new SelectListItem { Text = "Dr", Value = "Dr" });
            result.Add(new SelectListItem { Text = "Other", Value = "Other" });

            return result;
        }
    }
}

src/Loans.WebMvc/Models/Application/LoanSubmissionVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Loans.WebMvc.Models.Application
{
    public class LoanSubmissionVM
    {
        [DisplayName("Amount Of Credit")]
        public decimal CreditAmount { get; set; }

        [DisplayName("Total Amount Payable")]
        public decimal PayableAmount { get; set; }

        public int NumOfRepayments { get; set; }

        public decimal MonthlyPayment { get; set; }

        public string Repayments { get { return $"{NumOfRepayments} X £{Math.Round(MonthlyPayment, 2)}"; } }

        public decimal APR { get; set; }

        [DisplayName("Application Reference")]
        public string ApplicationRefrence { get; set; }
    }
}

src/Loans.WebMvc/Models/ErrorViewModel.cs
using System;

namespace Loans.WebMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string Message { get; set; }
    }
}

src/Loans.WebMvc/Controllers/LoanApplicationsController.cs
using System;
using System.Threading.Tasks;
using Loans.Engine;
using Loans.WebMvc.Infrastructure;
using Loans.WebMvc.Infrastructure.dto;
using Loans.WebMvc.Models;
using Loans.WebMvc.Models.Application;
using Microsoft.AspNetCore.Mvc;

namespace Loans.WebMvc.Controllers
{
    public class LoanApplicationsController : Controller
    {
        private readonly ILoanCalculations loanCalculations;
        private readonly ILoanService loanService;

        public LoanApplicationsController(
            ILoanCalculations loanCalculations,
            ILoanService loanService)
        {
            this.loanCalculations = loanCalculations;
            this.loanService = loanService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new LoanApplicationVM());
        }

        [HttpPost]
        public async Task<ActionResult> Create(LoanApplicationVM vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // get APR calculations
                    var aprResult = loanCalculations.GetAPR(17.3m, 18, vm.LoanRequestAmount);

                    var submissionVm = new LoanSubmissionVM
                    {
                        CreditAmount = aprResult.CreditAmount,
                        MonthlyPayment = aprResult.RepaymentAmount,
                        NumOfRepayments = aprResult.RepaymentTerm,
                        PayableAmount = aprResult.TotalAmountPayable,
                        APR = aprResult.APR
                    };

                    var loanDto = Map(vm, submissionVm);
                    var applicationRefrence = await loanService.Save(loanDto);
                    submissionVm.ApplicationRefrence = applicationRefrence;

                    return View("Submission", submissionVm);
                }
                else
                {
                    return View("Error", new ErrorViewModel() { Message = "Invalid data, please try again" });
                }
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel() { Message = ex.Message });
            }
        }

        private static LoanApplicationDto Map(LoanApplicationVM loanApplicationVM, LoanSubmissionVM loanSubmissionVM)
        {
            return new LoanApplicationDto()
            {
                User = new UserDto()
                {
                    Address = loanApplicationVM.Address,
                    AnnualIncomeInThousands = loanApplicationVM.AnnualIncome,
                    CarRegistrationNumber = loanApplicationVM.CarRegistrationNumber,
                    Email = loanApplicationVM.EmailAddress,
                    FirstName = loanApplicationVM.FirstName,
                    LastName = loanApplicationVM.Lastname,
                    IsHomeOwner = loanApplicationVM.IsHomeOwner,
                    Mobile = loanApplicationVM.MobileNumber,
                },
                APR = loanSubmissionVM.APR,
                RequestAmount = loanApplicationVM.LoanRequestAmount,
                TotalAmountPayable = loanSubmissionVM.PayableAmount,
                MonthlyPayment = loanSubmissionVM.MonthlyPayment,
                TermLengthInMonths = loanSubmissionVM.NumOfRepayments
            };
        }
    }
}

src/Loans.WebMvc/Views/LoanApplications/Create.cshtml
@model Loans.WebMvc.Models.Application.LoanApplicationVM

@{
    ViewData["Title"] = "Create";
}

<h1>Your Loan Application</h1>
<hr />
<div class="container">

    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <section>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>

                        @Html.DropDownListFor(model => model.Title,
                                (List<SelectListItem>)Model.Titles, "Select Title", htmlAttributes: new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Lastname" class="control-label"></label>
                        <input asp-for="Lastname" class="form-control" />
                        <span asp-validation-for="Lastname" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="MobileNumber" class="control-label"></label>
                        <input asp-for="MobileNumber" class="form-control" />
                        <span asp-validation-for="MobileNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EmailAddress" class="control-label"></label>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.DisplayNameFor(model => model.IsHomeOwner)
                        <label class="switch">
                            <input type="checkbox" asp-for="IsHomeOwner">
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        (£) <label asp-for="AnnualIncome" class="control-label"></label>
                        <input asp-for="AnnualIncome" class="form-control" />
                        <span asp-validation-for="AnnualIncome" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CarRegistrationNumber" class="control-label"></label>
                        <input asp-for="CarRegistrationNumber" class="form-control" />
                        <span asp-validation-for="CarRegistrationNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        (£) <label asp-for="LoanRequestAmount" class="control-label"></label>
                        <input asp-for="LoanRequestAmount" class="form-control" />
                        <span asp-validation-for="LoanRequestAmount" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </section>
    </form>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Loans.WebMvc/Views/LoanApplications/Submission.cshtml
@model Loans.WebMvc.Models.Application.LoanSubmissionVM

@{
    ViewData["Title"] = "Submission";
}

<div class="container">
    <h4>Your application will now be evaluated</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.ApplicationRefrence)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.ApplicationRefrence)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.CreditAmount)
        </dt>
        <dd class="col-sm-6">
            £@Model.CreditAmount.ToString("N2")
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PayableAmount)
        </dt>
        <dd class="col-sm-6">
            £@Model.PayableAmount.ToString("N2")
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Repayments)
        </dt>
        <dd class="col-sm-6">
            @Model.Repayments
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.APR)
        </dt>
        <dd class="col-sm-6">
            £@Model.APR.ToString("N2")%
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Create New", "Create") |
</div>

src/Loans.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loans</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/toggleSwitch.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="LoanApplications" asp-action="Create">New Application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
              
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Loans
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>